# A Docker Compose must always start with the version tag.
version: '3'

# We use the keyword 'services' to start to create services.
services:
  # The name of our service is "database"
  database:
    # Postgres image from DockerHub (we use the latest version)
    image: 'postgres:latest'

    # By default, a Postgres database is running on the 5432 port.
    # If we want to access the database from our computer (outside the container),
    # we must share the port with our computer's port.
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: username # useful to connect to the database
      POSTGRES_PASSWORD: password # useful to connect to the database
      POSTGRES_DB: default_database # default database